import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View, type TextStyle, type ViewStyle } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/Screen';
import { AppButton } from '../components/AppButton';
import { Input } from '../components/ui';
import { colors } from '../constants/theme';
import { getHealth } from '../services/api/health';
import { login, register } from '../services/authService';
import type { RootStackParamList } from '../types';

type Props = NativeStackScreenProps<RootStackParamList, 'Login'>;
export function LoginScreen({ route, navigation }: Props) {
  const [api, setApi] = useState('Checking API…'); const [createMode, setCreateMode] = useState(false); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  useEffect(() => { getHealth().then(() => setApi('Backend connected')).catch(() => setApi('Backend unavailable')); }, []);
  const validEmail = email.includes('@') && email.includes('.'); const validForm = validEmail && password.length >= 8 && (!createMode || name.trim().length >= 2);
  const submit = async () => { if (!validForm) { setError(createMode ? 'Enter your name, a valid email, and an 8-character password.' : 'Enter a valid email and an 8-character password.'); return; } setError(''); setLoading(true); try { if (createMode) await register(name.trim(), email.trim(), password, route.params.role); else await login(email.trim(), password); navigation.navigate('Home', { role: route.params.role }); } catch (cause) { const message = cause instanceof Error ? cause.message : ''; setError(message.includes('401') || message.toLowerCase().includes('invalid email') ? 'Incorrect email or password. Create an account first if you are new.' : message.includes('409') || message.toLowerCase().includes('already registered') ? 'This email is already registered. Sign in instead.' : 'We could not complete that request. Check your connection and try again.'); } finally { setLoading(false); } };
  return <Screen><View style={s.header}><Text style={s.kicker}>{route.params.role} PORTAL</Text><Text style={s.title}>{createMode ? 'Create your account.' : 'Welcome back.'}</Text><Text style={s.status}>{api}</Text></View><View style={s.form}>{createMode && <Input label="Full name" value={name} onChangeText={setName} placeholder="Your name" autoCapitalize="words" tone="dark"/>}<Input label="Email address" value={email} onChangeText={setEmail} placeholder="name@example.com" autoCapitalize="none" keyboardType="email-address" autoComplete="email" tone="dark" error={error && !validEmail ? error : undefined}/><Input label="Password" value={password} onChangeText={setPassword} placeholder="At least 8 characters" secureTextEntry autoComplete={createMode ? 'new-password' : 'current-password'} tone="dark" error={error && validEmail ? error : undefined}/><AppButton label={createMode ? 'Create account' : 'Continue'} loading={loading} disabled={loading} onPress={submit}/><Pressable accessibilityRole="button" onPress={() => { setCreateMode((value) => !value); setError(''); }}><Text style={s.switch}>{createMode ? 'Already have an account? Sign in' : 'New owner or driver? Create an account'}</Text></Pressable><Text style={s.note}>Use a real account to connect securely to live tracking.</Text></View></Screen>;
}
const s=StyleSheet.create<{header:ViewStyle;kicker:TextStyle;title:TextStyle;status:TextStyle;form:ViewStyle;switch:TextStyle;note:TextStyle}>({header:{marginTop:60,marginBottom:48},kicker:{color:colors.green,fontSize:11,letterSpacing:2,fontWeight:'700'},title:{fontSize:42,color:colors.text,fontWeight:'800',marginTop:12},status:{color:colors.muted,marginTop:12},form:{gap:13},switch:{color:colors.green,textAlign:'center',fontWeight:'700',fontSize:13,paddingVertical:8},note:{color:colors.muted,fontSize:12,lineHeight:18,textAlign:'center',marginTop:5}});
