export interface IndianBankData {
  code: string; // 4-letter IFSC prefix
  name: string;
  shortName: string;
  category: 'PUBLIC' | 'PRIVATE' | 'SMALL_FINANCE' | 'PAYMENTS' | 'FOREIGN' | 'COOPERATIVE';
  logoUrl: string;
  logoEmoji: string;
  brandColor: string;
  sampleIfsc: string;
  defaultBranch: string;
  upiHandles: string[];
}

export const ALL_INDIAN_BANKS: IndianBankData[] = [
  // --- PUBLIC SECTOR BANKS ---
  {
    code: 'SBIN',
    name: 'State Bank of India',
    shortName: 'SBI',
    category: 'PUBLIC',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/sbi.png',
    logoEmoji: '🏛️',
    brandColor: '#280071',
    sampleIfsc: 'SBIN0000840',
    defaultBranch: 'Main Branch, MG Road, Bengaluru',
    upiHandles: ['@oksbi', '@sbi'],
  },
  {
    code: 'PUNB',
    name: 'Punjab National Bank',
    shortName: 'PNB',
    category: 'PUBLIC',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/pnb.png',
    logoEmoji: '🏢',
    brandColor: '#A20F34',
    sampleIfsc: 'PUNB0021900',
    defaultBranch: 'Connaught Place Branch, New Delhi',
    upiHandles: ['@pnb', '@paytm'],
  },
  {
    code: 'BARB',
    name: 'Bank of Baroda',
    shortName: 'BOB',
    category: 'PUBLIC',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/bob.png',
    logoEmoji: '🌐',
    brandColor: '#F26522',
    sampleIfsc: 'BARB0INDIRA',
    defaultBranch: 'Indiranagar Branch, Bengaluru',
    upiHandles: ['@barodampay'],
  },
  {
    code: 'CNRB',
    name: 'Canara Bank',
    shortName: 'Canara',
    category: 'PUBLIC',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/canara.png',
    logoEmoji: '🏦',
    brandColor: '#00529C',
    sampleIfsc: 'CNRB0001002',
    defaultBranch: 'Town Hall Branch, Bengaluru',
    upiHandles: ['@cnrb', '@canarabank'],
  },
  {
    code: 'UBIN',
    name: 'Union Bank of India',
    shortName: 'Union Bank',
    category: 'PUBLIC',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/union.png',
    logoEmoji: '🏛️',
    brandColor: '#003366',
    sampleIfsc: 'UBIN0530018',
    defaultBranch: 'Fort Branch, Mumbai',
    upiHandles: ['@unionbank', '@uboi'],
  },
  {
    code: 'BKID',
    name: 'Bank of India',
    shortName: 'BOI',
    category: 'PUBLIC',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/boi.png',
    logoEmoji: '⭐',
    brandColor: '#E41E26',
    sampleIfsc: 'BKID0008000',
    defaultBranch: 'Star House Main Branch, Mumbai',
    upiHandles: ['@boi'],
  },
  {
    code: 'IDIB',
    name: 'Indian Bank',
    shortName: 'Indian Bank',
    category: 'PUBLIC',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/indianbank.png',
    logoEmoji: '🏛️',
    brandColor: '#004A8F',
    sampleIfsc: 'IDIB000M001',
    defaultBranch: 'Mount Road Main Branch, Chennai',
    upiHandles: ['@indianbank', '@indianbk'],
  },
  {
    code: 'CBIN',
    name: 'Central Bank of India',
    shortName: 'Central Bank',
    category: 'PUBLIC',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/centralbank.png',
    logoEmoji: '🏦',
    brandColor: '#0072BC',
    sampleIfsc: 'CBIN0280001',
    defaultBranch: 'Chandni Chowk Branch, Delhi',
    upiHandles: ['@centralbank', '@cbin'],
  },
  {
    code: 'IOBA',
    name: 'Indian Overseas Bank',
    shortName: 'IOB',
    category: 'PUBLIC',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/iob.png',
    logoEmoji: '🌊',
    brandColor: '#0A3969',
    sampleIfsc: 'IOBA0000001',
    defaultBranch: 'Anna Salai Main Branch, Chennai',
    upiHandles: ['@iob'],
  },
  {
    code: 'UCBA',
    name: 'UCO Bank',
    shortName: 'UCO Bank',
    category: 'PUBLIC',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/uco.png',
    logoEmoji: '🤝',
    brandColor: '#0055A5',
    sampleIfsc: 'UCBA0000001',
    defaultBranch: 'BTM Layout Branch, Bengaluru',
    upiHandles: ['@uco'],
  },
  {
    code: 'MAHB',
    name: 'Bank of Maharashtra',
    shortName: 'Maha Bank',
    category: 'PUBLIC',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/mahabank.png',
    logoEmoji: '🏰',
    brandColor: '#F58220',
    sampleIfsc: 'MAHB0000001',
    defaultBranch: 'Shivajinagar Main Branch, Pune',
    upiHandles: ['@mahb', '@mahaconnect'],
  },
  {
    code: 'PSIB',
    name: 'Punjab & Sind Bank',
    shortName: 'PSB',
    category: 'PUBLIC',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/psb.png',
    logoEmoji: '🏬',
    brandColor: '#E31E24',
    sampleIfsc: 'PSIB0000001',
    defaultBranch: 'Rajendra Place Branch, New Delhi',
    upiHandles: ['@psb'],
  },

  // --- PRIVATE SECTOR BANKS ---
  {
    code: 'HDFC',
    name: 'HDFC Bank',
    shortName: 'HDFC',
    category: 'PRIVATE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/hdfc.png',
    logoEmoji: '🏦',
    brandColor: '#004B8D',
    sampleIfsc: 'HDFC0000240',
    defaultBranch: 'MG Road Main Branch, Bengaluru',
    upiHandles: ['@okhdfcbank', '@hdfcbank'],
  },
  {
    code: 'ICIC',
    name: 'ICICI Bank',
    shortName: 'ICICI',
    category: 'PRIVATE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/icici.png',
    logoEmoji: '💳',
    brandColor: '#F37021',
    sampleIfsc: 'ICIC0000102',
    defaultBranch: 'Indiranagar 100ft Rd Branch, Bengaluru',
    upiHandles: ['@icici', '@okicici'],
  },
  {
    code: 'UTIB',
    name: 'Axis Bank',
    shortName: 'Axis Bank',
    category: 'PRIVATE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/axis.png',
    logoEmoji: '⚡',
    brandColor: '#97144D',
    sampleIfsc: 'UTIB0000456',
    defaultBranch: 'Electronic City Tech Park Branch, Bengaluru',
    upiHandles: ['@axisbank', '@okaxis'],
  },
  {
    code: 'KKBK',
    name: 'Kotak Mahindra Bank',
    shortName: 'Kotak Bank',
    category: 'PRIVATE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/kotak.png',
    logoEmoji: '💰',
    brandColor: '#ED1C24',
    sampleIfsc: 'KKBK0008080',
    defaultBranch: 'Whitefield Main Campus Branch, Bengaluru',
    upiHandles: ['@kotak', '@kaypay'],
  },
  {
    code: 'INDB',
    name: 'IndusInd Bank',
    shortName: 'IndusInd',
    category: 'PRIVATE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/indusind.png',
    logoEmoji: '🐆',
    brandColor: '#84151B',
    sampleIfsc: 'INDB0000001',
    defaultBranch: 'Barakhamba Road Branch, New Delhi',
    upiHandles: ['@indus'],
  },
  {
    code: 'YESB',
    name: 'YES Bank',
    shortName: 'YES Bank',
    category: 'PRIVATE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/yesbank.png',
    logoEmoji: '✔',
    brandColor: '#005A9C',
    sampleIfsc: 'YESB0000001',
    defaultBranch: 'Nehru Place Branch, New Delhi',
    upiHandles: ['@yesbank', '@ybl'],
  },
  {
    code: 'FDRL',
    name: 'Federal Bank',
    shortName: 'Federal Bank',
    category: 'PRIVATE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/federal.png',
    logoEmoji: '🦅',
    brandColor: '#003A70',
    sampleIfsc: 'FDRL0001234',
    defaultBranch: 'Aluva Main Branch, Kochi',
    upiHandles: ['@federal'],
  },
  {
    code: 'IDFB',
    name: 'IDFC FIRST Bank',
    shortName: 'IDFC FIRST',
    category: 'PRIVATE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/idfc.png',
    logoEmoji: '🥇',
    brandColor: '#9E1B32',
    sampleIfsc: 'IDFB0040101',
    defaultBranch: 'Koramangala 80ft Rd Branch, Bengaluru',
    upiHandles: ['@idfcbank'],
  },
  {
    code: 'KVBL',
    name: 'Karur Vysya Bank',
    shortName: 'KVB',
    category: 'PRIVATE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/kvb.png',
    logoEmoji: '🛡️',
    brandColor: '#00833E',
    sampleIfsc: 'KVBL0001101',
    defaultBranch: 'Karur Main Branch, Tamil Nadu',
    upiHandles: ['@kvb'],
  },
  {
    code: 'SIBL',
    name: 'South Indian Bank',
    shortName: 'SIB',
    category: 'PRIVATE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/sib.png',
    logoEmoji: '🌴',
    brandColor: '#C41230',
    sampleIfsc: 'SIBL0000001',
    defaultBranch: 'Thrissur Main Branch, Kerala',
    upiHandles: ['@sib'],
  },
  {
    code: 'CIUB',
    name: 'City Union Bank',
    shortName: 'CUB',
    category: 'PRIVATE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/cub.png',
    logoEmoji: '🦁',
    brandColor: '#004A8F',
    sampleIfsc: 'CIUB0000001',
    defaultBranch: 'Kumbakonam Main Branch, Tamil Nadu',
    upiHandles: ['@cub'],
  },
  {
    code: 'RATN',
    name: 'RBL Bank',
    shortName: 'RBL Bank',
    category: 'PRIVATE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/rbl.png',
    logoEmoji: '💎',
    brandColor: '#002B49',
    sampleIfsc: 'RATN0000001',
    defaultBranch: 'Lower Parel Branch, Mumbai',
    upiHandles: ['@rbl'],
  },
  {
    code: 'BDBL',
    name: 'Bandhan Bank',
    shortName: 'Bandhan',
    category: 'PRIVATE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/bandhan.png',
    logoEmoji: '🔥',
    brandColor: '#F37023',
    sampleIfsc: 'BDBL0000001',
    defaultBranch: 'Salt Lake Sector V Branch, Kolkata',
    upiHandles: ['@bandhan'],
  },
  {
    code: 'JAKA',
    name: 'Jammu & Kashmir Bank',
    shortName: 'J&K Bank',
    category: 'PRIVATE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/jkbank.png',
    logoEmoji: '🏔️',
    brandColor: '#00529B',
    sampleIfsc: 'JAKA0000001',
    defaultBranch: 'Residency Road Branch, Srinagar',
    upiHandles: ['@jkbank'],
  },

  // --- SMALL FINANCE & PAYMENTS BANKS ---
  {
    code: 'AUBL',
    name: 'AU Small Finance Bank',
    shortName: 'AU Bank',
    category: 'SMALL_FINANCE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/aubank.png',
    logoEmoji: '🔶',
    brandColor: '#E65100',
    sampleIfsc: 'AUBL0002001',
    defaultBranch: 'Jaipur Main Branch, Rajasthan',
    upiHandles: ['@aubank'],
  },
  {
    code: 'ESFB',
    name: 'Equitas Small Finance Bank',
    shortName: 'Equitas',
    category: 'SMALL_FINANCE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/equitas.png',
    logoEmoji: '⚖️',
    brandColor: '#0071CE',
    sampleIfsc: 'ESFB0001001',
    defaultBranch: 'Chennai Central Branch, Tamil Nadu',
    upiHandles: ['@equitas'],
  },
  {
    code: 'UJJV',
    name: 'Ujjivan Small Finance Bank',
    shortName: 'Ujjivan',
    category: 'SMALL_FINANCE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/ujjivan.png',
    logoEmoji: '✨',
    brandColor: '#00529C',
    sampleIfsc: 'UJJV0001001',
    defaultBranch: 'Koramangala 4th Block Branch, Bengaluru',
    upiHandles: ['@ujjivan'],
  },
  {
    code: 'PYTM',
    name: 'Paytm Payments Bank',
    shortName: 'Paytm Bank',
    category: 'PAYMENTS',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/paytm.png',
    logoEmoji: '📲',
    brandColor: '#002E6E',
    sampleIfsc: 'PYTM0123456',
    defaultBranch: 'Noida Tech Park Branch, UP',
    upiHandles: ['@paytm'],
  },
  {
    code: 'AIRP',
    name: 'Airtel Payments Bank',
    shortName: 'Airtel Bank',
    category: 'PAYMENTS',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/airtel.png',
    logoEmoji: '📶',
    brandColor: '#E40000',
    sampleIfsc: 'AIRP0000001',
    defaultBranch: 'Gurugram Cyber City Branch, Haryana',
    upiHandles: ['@airtel'],
  },
  {
    code: 'IPPB',
    name: 'India Post Payments Bank',
    shortName: 'IPPB (Post Office)',
    category: 'PAYMENTS',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/ippb.png',
    logoEmoji: '📮',
    brandColor: '#D32F2F',
    sampleIfsc: 'IPPB0000001',
    defaultBranch: 'General Post Office GPO, New Delhi',
    upiHandles: ['@postbank'],
  },

  // --- COOPERATIVE BANKS ---
  {
    code: 'SRCB',
    name: 'Saraswat Cooperative Bank',
    shortName: 'Saraswat Bank',
    category: 'COOPERATIVE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/saraswat.png',
    logoEmoji: '🪕',
    brandColor: '#1A365D',
    sampleIfsc: 'SRCB0000001',
    defaultBranch: 'Prabhadevi Main Branch, Mumbai',
    upiHandles: ['@saraswat'],
  },
  {
    code: 'COSB',
    name: 'Cosmos Cooperative Bank',
    shortName: 'Cosmos Bank',
    category: 'COOPERATIVE',
    logoUrl: 'https://raw.githubusercontent.com/swapee/indian-bank-logos/main/logos/cosmos.png',
    logoEmoji: '🌌',
    brandColor: '#0D47A1',
    sampleIfsc: 'COSB0000001',
    defaultBranch: 'University Road Branch, Pune',
    upiHandles: ['@cosmos'],
  },
];

export function findBankByCodeOrName(query: string): IndianBankData | undefined {
  if (!query || !query.trim()) return undefined;
  const q = query.trim().toLowerCase();
  
  // Direct code match (e.g. SBIN, HDFC, CNRB)
  const codeMatch = ALL_INDIAN_BANKS.find((b) => b.code.toLowerCase() === q);
  if (codeMatch) return codeMatch;

  // Name match
  return ALL_INDIAN_BANKS.find(
    (b) =>
      b.shortName.toLowerCase() === q ||
      b.name.toLowerCase().includes(q) ||
      q.includes(b.shortName.toLowerCase())
  );
}

export function searchIndianBanks(query: string): IndianBankData[] {
  if (!query || !query.trim()) return ALL_INDIAN_BANKS;
  const q = query.trim().toLowerCase();
  return ALL_INDIAN_BANKS.filter(
    (b) =>
      b.name.toLowerCase().includes(q) ||
      b.shortName.toLowerCase().includes(q) ||
      b.code.toLowerCase().includes(q)
  );
}
